# Generated by Django 2.2.3 on 2019-07-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.SmallIntegerField()),
                ('num_games', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, null=True)),
                ('start_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('avatar', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('tournament_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Tournament')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentJudge',
            fields=[
                ('tournament_judge_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Tournament')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_creator_id', to='api.User'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='judges',
            field=models.ManyToManyField(related_name='tournament_judges', through='api.TournamentJudge', to='api.User'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(related_name='tournament_users', through='api.TournamentUser', to='api.User'),
        ),
        migrations.CreateModel(
            name='MatchUser',
            fields=[
                ('match_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Match')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='judge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_judge_id', to='api.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(through='api.MatchUser', to='api.User'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Match')),
                ('winner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
    ]
