# Generated by Django 2.2.3 on 2019-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190704_1755'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchuser',
            table='match_user',
        ),
        migrations.AlterModelTable(
            name='tournamentjudge',
            table='tournament_judge',
        ),
        migrations.AlterModelTable(
            name='tournamentuser',
            table='tournament_user',
        ),
    ]
