# Generated by Django 2.2.3 on 2019-07-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190729_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
