# Generated by Django 2.2.3 on 2019-07-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190729_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winner_id',
            new_name='winner',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='matchuser',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='matchuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tournamentuser',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='tournamentuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
