# Generated by Django 2.2.3 on 2019-07-30 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190729_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchuser',
            name='is_judge',
        ),
        migrations.AlterField(
            model_name='match',
            name='num_games',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
