# Generated by Django 2.2.3 on 2019-08-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190801_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='prev_matches',
            field=models.ManyToManyField(null=True, related_name='_match_prev_matches_+', to='api.Match'),
        ),
    ]
