# Generated by Django 2.2.3 on 2019-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_match_prev_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='prev_matches',
            field=models.ManyToManyField(default=None, related_name='_match_prev_matches_+', to='api.Match'),
        ),
    ]
