# Generated by Django 2.2.3 on 2019-08-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190805_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='prev_matches',
        ),
        migrations.AddField(
            model_name='match',
            name='prev_matches',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Match'),
        ),
    ]
