# Generated by Django 2.2.3 on 2019-08-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190805_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='prev_matches',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Match'),
        ),
    ]
