# Generated by Django 2.2.3 on 2019-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190805_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='prev_matches',
            field=models.ManyToManyField(blank=True, to='api.Match'),
        ),
    ]
