# Generated by Django 2.2.4 on 2019-08-07 17:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190806_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='prev_matches',
        ),
        migrations.AddField(
            model_name='match',
            name='prev_matches',
            field=mptt.fields.TreeForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='next_parents', to='api.Match'),
            preserve_default=False,
        ),
    ]
