# Generated by Django 2.2.4 on 2019-08-07 17:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190807_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='prev_matches',
        ),
        migrations.AddField(
            model_name='match',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Match'),
            preserve_default=False,
        ),
    ]
