# Generated by Django 2.2.4 on 2019-08-07 17:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190807_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Match'),
        ),
    ]
