# Generated by Django 2.2.5 on 2019-09-03 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190810_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournament_users', through='api.TournamentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
