version: '3.3'

services:
  db:
    build: ./db
    restart: always
    env_file:
      - ./db/db-dev.env
    container_name: sockem-boppem_db

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./db/db-dev.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  jenkins:
    build: ./jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - ./backend:/app/backend

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin4/pgadmin-dev.env
    depends_on:
      - db
    ports:
      - "5555:5555"

volumes:
  jenkins_data:
    driver: local
  node-modules: